name: Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm ci; else echo "No package.json, skipping"; fi

      - name: Validate JSON schema
        run: |
          if [ -f package.json ]; then npm run validate-json; fi

      - name: Prepare public folder
        run: |
          mkdir public
          shopt -s extglob
          cp -r !(public|node_modules|.git|.github) public/ 2>/dev/null || true
          # Si hay node modules que quieras servir (no debería), se ajustaría aquí
          echo "Listado de archivos copiados:" 
          find public -maxdepth 4 -type f | head -n 200

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
