name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm ci; else echo "No package.json, skipping npm ci"; fi

      - name: Run validation and lint (CI)
        run: |
          npm run ci

      - name: Build (no-op)
        run: echo "No build step required for this static site"

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
